### ISSUE TITLE
MyNet? from Q_sam_ergas import my_compute_sam_ergas

### ISSUE THREAD

**Issue by renxiaosa00** [liangjiandeng/Hyper-DSNet#1]
1 class Hyper_DSNet(nn.Module):
    def __init__(self):
        super(MYNet, self).__init__() ,  MYNet is null
2 from Q_sam_ergas import my_compute_sam_ergas  is null

**Comment by Pluto-wei** [comment]
Thanks for your reminder.
It has been corrected, please check.

1 MYNet change to Hyper_DSNet
2 add Q_sam_ergas
